name: Deploy to Vercel

on:
  push:
    branches: [main]

concurrency:
  group: vercel-production
  cancel-in-progress: true

jobs:
  deploy:
    uses: yearn/gha/.github/workflows/vercel-1password-deploy.yml@main
    with:
      VERCEL_PROJECT_ID: op://webops-prod/v2-fapy/VERCEL_PROJECT_ID
      secrets: |
        KONG_SECRET=op://webops-prod/v2-fapy/KONG_SECRET
        CRV_GAUGE_REGISTRY_URL=op://webops-prod/v2-fapy/CRV_GAUGE_REGISTRY_URL
        CRV_POOLS_URL=op://webops-prod/v2-fapy/CRV_POOLS_URL
        RPC_CHAIN_URL_1=op://webops-prod/v2-fapy/RPC_CHAIN_URL_1
        RPC_CHAIN_URL_10=op://webops-prod/v2-fapy/RPC_CHAIN_URL_10
        RPC_CHAIN_URL_100=op://webops-prod/v2-fapy/RPC_CHAIN_URL_100
        RPC_CHAIN_URL_137=op://webops-prod/v2-fapy/RPC_CHAIN_URL_137
        RPC_CHAIN_URL_146=op://webops-prod/v2-fapy/RPC_CHAIN_URL_146
        RPC_CHAIN_URL_250=op://webops-prod/v2-fapy/RPC_CHAIN_URL_250
        RPC_CHAIN_URL_42161=op://webops-prod/v2-fapy/RPC_CHAIN_URL_42161
        RPC_CHAIN_URL_747474=op://webops-prod/v2-fapy/RPC_CHAIN_URL_747474
        RPC_CHAIN_URL_80094=op://webops-prod/v2-fapy/RPC_CHAIN_URL_80094
        RPC_CHAIN_URL_8453=op://webops-prod/v2-fapy/RPC_CHAIN_URL_8453
      export-env: true
    secrets: inherit
