name: Deploy to Vercel

on:
  push:
    branches: [main]

concurrency:
  group: vercel-production
  cancel-in-progress: false

permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  deploy:
    uses: yearn/yearn-gha/.github/workflows/vercel-deploy.yml@main
    with:
      vault: webops-prod-katana-apr-service
      environment: production
      secrets: |
        VERCEL_PROJECT_ID=VERCEL_PROJECT_ID
        RPC_URL_KATANA=RPC_URL_KATANA
        KONG_WEBHOOK_SECRET=KONG_WEBHOOK_SECRET
        COINGECKO_API_KEY=COINGECKO_API_KEY
        KONG_BASE_URI=KONG_BASE_URI
        YDAEMON_BASE_URI=YDAEMON_BASE_URI
        MERKL_BASE_URI=MERKL_BASE_URI
        MERKL_API_KEY=MERKL_API_KEY
        COINGECKO_BASE_URI=COINGECKO_BASE_URI
        COINGECKO_KATANA_COIN_ID=COINGECKO_KATANA_COIN_ID
        KATANA_APR_SERVICE_API=KATANA_APR_SERVICE_API
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
